# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.0

EAPI="2"

MODULE_AUTHOR="JPB"

inherit perl-module

DESCRIPTION="Perl module interface to a nessus server."

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="amd64 ~amd64"
IUSE=""

DEPEND="dev-perl/Config-IniFiles
	perl-gcpan/Net-Nessus
	>=dev-perl/IO-Socket-SSL-1.33
	dev-lang/perl"
